spring.application.name=perfumeria

# Configuración crucial para Render (Puerto dinámico)
server.port=${PORT:8080}

# Base de Datos Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.mshlpehrumsqvucpjgtf.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=@VelvetEssence123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seguridad y Variables de Entorno de la Aplicación
app.security.jwt-secret=${JWT_SECRET:velvet-essence-development-secret-key-2026-strong}
app.security.seed-admin=${SEED_ADMIN:true}
app.security.admin-email=${ADMIN_EMAIL:admin@velvet.com}
app.security.admin-password=${ADMIN_PASSWORD:Admin123!}
