spring.application.name=perfumeria

#Base de Datos Mysql
spring.datasource.url=jdbc:mysql://localhost:3306/velvet_essence?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 'update' sincroniza la estructura de la BD con las Entidades Java sin borrar datos existentes
spring.jpa.hibernate.ddl-auto=update

#Trazabilidad de consultas de la Base de Datos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect